<?php

namespace app\admin\controller;

use think\Controller;
use think\Session;
use think\Cookie;

class Base extends Controller{

    //
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        define('ADMIN_ID',Session::has('admin_id')?Session::get('admin_id'):null);
        $this->isLogin();
    }

    //判断用户是否登陆，放在系统后台入口的前面： index/index
    protected function isLogin(){
        if (strpos($_SERVER['REQUEST_URI'],'login') == false){
            if (is_null(ADMIN_ID)){
                $this->error('用户未登陆，无权访问',url('admin/login'));
            }
        }
    }

    //防止用户重复登陆，放在登陆操作的前面：admin/login
    protected function alreadyLogin(){
        if (ADMIN_ID){
            $this->error('用户已登陆请勿重复登陆',url('index/index'));
        }
    }
}